### ISSUE TITLE
Add a 'Finish Meal' workflow with an ad included — Business value and restaurant value due to additional ratings, reviews and follows.

### ISSUE THREAD

**Issue by zcsullens** [Nomi-Technologies/web-menu#110]
![Image](https://user-images.githubusercontent.com/32182225/195960176-7e92f7ce-d7cd-4c8b-9436-fc90e367506f.png)

### Part 1: Create New Page to Finish the Meal

- [ ] Change button in bottom sheet from 'Done' to 'Finish Meal'
- [ ] Segue to new page as shown which pulls in the restaurant logo and the social links from the 'About Us' section.
- [ ] 'Start Over' button should bring the user back to the beginning to the loading screen etc.
- [ ] Add section for 'Sponsored Advertisements' below the button following [web-menu #90](https://github.com/Nomi-Technologies/web-menu/issues/90)
