### ISSUE TITLE
Create a workflow to get the user started on their menu journey — Provides end-user value and delight.

### ISSUE THREAD

**Issue by zcsullens** [Nomi-Technologies/web-menu#97]
![Image](https://user-images.githubusercontent.com/32182225/195959855-9acfb19a-8d8d-4fcf-a4ac-d4a775e7a5bb.png)

### Part 1: Loading Screen

![Image](https://user-images.githubusercontent.com/32182225/195959612-857aeb4a-d487-4936-866e-e8bd02d0cf03.gif)

- [x]  Place the following Gif in the middle of the screen at around 200-250 px wide. We may need to play with this size to figure out what looks best. This will replace the 'Your Restaurant is Loading' message.
- [x]  Below the animation should be a randomly selected quote from the following:
    - “One cannot think, love, sleep well if one has not dined well.” -Virginia Woolf
    - “If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.” -J.R.R. Tolkien
    - “People who love to eat are always the best people.” – Julia Child
    - “One of the very nicest things about life is the way we must regularly stop whatever it is we are doing and devote our attention to eating.”  – Luciano Pavarotti
    - “What I say is that, if a fellow really likes potatoes, he must be a pretty decent sort of fellow.” – A.A. Milne
    - “After a good dinner one can forgive anybody, even one’s own relatives.” – Oscar Wilde
- [x]  The loading screen should never take less than 2 seconds to allow for the quotes to be read.
- [x]  By the time the loading has finished, the entire app should be loaded and the user should have no issues viewing images or any other portion of the app

![Image](https://user-images.githubusercontent.com/32182225/195959792-f722d294-5f2d-4dd6-82da-6c1b254a9e4e.png)

### Part 2: Start and Filter

- [x] After the loading screen is done, the user should be shown the logo of the restaurant as displayed in the mockup with a button to 'View My Menu'.
- [x] The quote from loading should persist.
- [x] When the user pressed the start button, they should be shown a modified 'filters' sidebar panel
      - [ ] Hide the search bar
      - [ ] Change 'Done' to 'Skip'
      - [ ] Add sticky bottom bar with a button to 'Save & Continue'
      - [ ] Tapping on the bottom bar after adding filters should save the filters
      - [ ] Adding a filter should change 'Skip' to 'Done'
      - [ ] Tapping 'Done' should also save the filters.
